name: joaorb64
description: João Ribeiro Bezerra
markdown: kramdown
highlighter: pygments
about: Computer scientist. I work with games and game development. I also love Super Smash Bros.

urls:
    - text: github
      url: https://github.com/joaorb64
    - text: twitter
      url: https://twitter.com/joao_shino
