name: joaorb64
description: João Ribeiro Bezerra
markdown: kramdown
highlighter: pygments
about: Brazilian, Master in Computer Science. Linux and Super Smash Bros. fan.

baseurl: ""
baseurl2: https://joaorb64.github.io

collections: {
  projects: {
    output: true
  }
}

urls: [
  {
    site: "github",
    link: "https://github.com/joaorb64"
  },
  {
    site: "twitter",
    link: "https://twitter.com/joao_shino"
  },
  {
    site: "linkedin",
    link: "https://www.linkedin.com/in/joaorb64/"
  }
]